services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/reading-recommendation-system-api/src

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reading_recommendation_system_api_db
    ports:
      - '25060:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
